### PR TITLE
Fix unix dialog

### PR DESCRIPTION
**Pull request by lbartoletti**
Hi!

I made some change to use totalopenstationToQgis on my computer and to normalize the code.

I hope the commit messages are explicit.

I used black to see differences between windows and else parts.

### CODE REVIEW

**Comment by enzococca** [comment]
hi @lbartoletti, thanks for your suggest and your cooperation. 
your modification doesn't work for windows. before to merge I need understand where is the problem. I think the problem is in  normalize path https://github.com/enzococca/totalopenstationToQgis/pull/4/commits/0cdcc412fd74a8423b17ac1df31d577e4da9dd5c. this week im very busy but I will take look sunday.

**Comment by lbartoletti** [comment]
@enzococca Yes, there is a problem with [sys.executable on OSGeo4W](https://github.com/qgis/QGIS/issues/45646).

It's fixed with a slightly modified version of https://github.com/qgis/QGIS/issues/45646#issuecomment-950339443

**Comment by enzococca** [comment]
@lbartoletti I tried your update and not working for windows. Are you sure it works for unix? In windows sys.executable open a new QGIS proj and not upload the data. Seem it not read properly the totalopenstation-cli-parser.py. If change in 'python' instead to sys.executable it works but after qgis crash. I will try to modify something and I will let you know or if you have another solution please let me know. 

in python console of QGIS:

import sys
a= sys.executable
print(a)
C:\OSGeo4W\bin\qgis-bin.exe

So sys.executable not call python but qgis

**Comment by enzococca** [comment]
I add the function to check the path python excutable in windows. take a look if works for you

**Review by ghost — APPROVED** [review]

**Comment by lbartoletti** [comment]
> @lbartoletti I tried your update and not working for windows. Are you sure it works for unix? In windows sys.executable open a new QGIS proj and not upload the data. Seem it not read properly the totalopenstation-cli-parser.py. If change in 'python' instead to sys.executable it works but after qgis crash. I will try to modify something and I will let you know or if you have another solution please let me know.
> 
> in python console of QGIS:
> 
> import sys a= sys.executable print(a) C:\OSGeo4W\bin\qgis-bin.exe
> 
> So sys.executable not call python but qgis

Yes it's worked, see my comments and https://github.com/enzococca/totalopenstationToQgis/pull/4/commits/e0e36d2ef59d065dd6f4881e68015a85d82cdfc9#diff-2f55001d9ef69fc6f04d69c5d51d158508fab463c656bd34ca65a88861967cf9R64-R69

**Pull request merged**
